version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run: npm install
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
         root: .
         paths:
            - .
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - attach_workspace:
          at: .
      - run: pip3 install ansible
      - run: pip3 install boto boto3
      - run: echo ${PEM_FILE} | tr , '\n' > ansible.pem
      - run: chmod 400 ansible.pem
      - run: echo ${VAULT_PASS} > .vault_pass.txt
      - run:
         command: ansible-playbook ansible/ec2_deploy.yml --user ubuntu --key-file ansible.pem --vault-password-file .vault_pass.txt
         environment:
            ANSIBLE_HOST_KEY_CHECKING: False
workflows:
  version: 2.1
  build:
    jobs:
      - build
      - deploy:
         requires:
            - build
         filters:
            branches:
               only: master
