- name: Kill 'em all. 
  hosts: localhost
  connection: local
  
  tasks:
    - name: Kill all eshop instances 
      ec2:
        instance_type: t2.micro
        image: ami-085925f297f89fce1
        region: us-east-1
        key_name: ansible
        vpc_subnet_id: subnet-3afd7d77
        assign_public_ip: yes
        wait: yes
        group: eshop
        count_tag: 
          Name: eshop
        instance_tags:
          Name: eshop
        aws_access_key: "{{aws_access_key_id}}"
        aws_secret_key: "{{aws_secret_access_key}}"
        security_token: "{{aws_session_token}}"
        exact_count: 0
      register: ec2